Repository fjelltopp/ckanext-who-afro, pull requests merged in 2024-10, with the labels that each got.

#80 Fix search bar focus and typographical error in datasets page.
  ckanext/who_afro/assets/css/who-afro.css
  ckanext/who_afro/templates/package/search.html
Labels: minor

#78 [#129] Make sure to return only indicators during search on the indicators list page
  ckanext/who_afro/templates/group/read.html
Labels: patch

#83 fix: prevent robots crawling the site
  ckanext/who_afro/templates/home/robots.txt
Labels: bug, patch
