Repository fjelltopp/ckanext-who-afro, pull requests merged in 2024-07, with the labels that each got.

#33 WAC-30 Metadata changes
  .github/workflows/test.yml
  ckanext/who_afro/assets/css/who-afro.css
  ckanext/who_afro/helpers.py
  ckanext/who_afro/licenses.json
  ckanext/who_afro/plugin.py
  ckanext/who_afro/presets.json
  ckanext/who_afro/schemas/dataset.yaml
  ckanext/who_afro/schemas/indicator.yaml
  ckanext/who_afro/schemas/publication.yaml
  ckanext/who_afro/schemas/source.yaml
  ckanext/who_afro/templates/scheming/display_snippets/language.html
  ckanext/who_afro/templates/scheming/display_snippets/multiple_inline.html
  ckanext/who_afro/templates/scheming/form_snippets/language.html
  ckanext/who_afro/templates/scheming/package/snippets/additional_info.html
  ckanext/who_afro/tests/schemas/language_validator.yaml
  ckanext/who_afro/tests/schemas/who_license_autofill.yaml
  ckanext/who_afro/tests/test_helpers.py
  ckanext/who_afro/tests/test_validators.py
  ckanext/who_afro/validators.py
  dev-requirements.txt
  test.ini
Labels: major

#34 fix: add yaml map name
  ckanext/who_afro/schemas/dataset.yaml
Labels: bug, patch

#35 feat: add countries menu and landing page
  ckanext/who_afro/assets/css/who-afro.css
  ckanext/who_afro/blueprints/__init__.py
  ckanext/who_afro/blueprints/countries.py
  ckanext/who_afro/public/images/country-flags/algeria.png
  ckanext/who_afro/public/images/country-flags/angola.png
  ckanext/who_afro/public/images/country-flags/benin.png
  ckanext/who_afro/public/images/country-flags/botswana.png
  ckanext/who_afro/public/images/country-flags/burkina-faso.png
  ckanext/who_afro/public/images/country-flags/burundi.png
  ckanext/who_afro/public/images/country-flags/cabo-verde.png
  ckanext/who_afro/public/images/country-flags/cameroon.png
  ckanext/who_afro/public/images/country-flags/central-african-republic.png
  ckanext/who_afro/public/images/country-flags/chad.png
  ckanext/who_afro/public/images/country-flags/comoros.png
  ckanext/who_afro/public/images/country-flags/congo.png
  ckanext/who_afro/public/images/country-flags/cote-divoire.png
  ckanext/who_afro/public/images/country-flags/democratic-republic-of-congo.png
  ckanext/who_afro/public/images/country-flags/equatorial-guinea.png
  ckanext/who_afro/public/images/country-flags/eritrea.png
  ckanext/who_afro/public/images/country-flags/eswatini.png
  ckanext/who_afro/public/images/country-flags/ethiopia.png
  ckanext/who_afro/public/images/country-flags/gabon.png
  ckanext/who_afro/public/images/country-flags/ghana.png
  ckanext/who_afro/public/images/country-flags/guinea-bissau.png
  ckanext/who_afro/public/images/country-flags/guinea.png
  ckanext/who_afro/public/images/country-flags/kenya.png
  ckanext/who_afro/public/images/country-flags/lesotho.png
  ckanext/who_afro/public/images/country-flags/liberia.png
  ckanext/who_afro/public/images/country-flags/madagascar.png
  ckanext/who_afro/public/images/country-flags/malawi.png
  ckanext/who_afro/public/images/country-flags/mali.png
  ckanext/who_afro/public/images/country-flags/mauritania.png
  ckanext/who_afro/public/images/country-flags/mauritius.png
  ckanext/who_afro/public/images/country-flags/mozambique.png
  ckanext/who_afro/public/images/country-flags/namibia.png
  ckanext/who_afro/public/images/country-flags/niger.png
  ckanext/who_afro/public/images/country-flags/nigeria.png
  ckanext/who_afro/public/images/country-flags/rwanda.png
  ckanext/who_afro/public/images/country-flags/sao-tome-and-principe.png
  ckanext/who_afro/public/images/country-flags/senegal.png
  ckanext/who_afro/public/images/country-flags/seychelles.png
  ckanext/who_afro/public/images/country-flags/sierra-leone.png
  ckanext/who_afro/public/images/country-flags/south-africa.png
  ckanext/who_afro/public/images/country-flags/south-sudan.png
  ckanext/who_afro/public/images/country-flags/the-gambia.png
  ckanext/who_afro/public/images/country-flags/togo.png
  ckanext/who_afro/public/images/country-flags/uganda.png
  ckanext/who_afro/public/images/country-flags/united-republic-of-tanzania.png
  ckanext/who_afro/public/images/country-flags/zambia.png
  ckanext/who_afro/public/images/country-flags/zimbabwe.png
  ckanext/who_afro/templates/countries/index.html
  ckanext/who_afro/templates/header.html
  ckanext/who_afro/templates/insights/featured.html
Labels: enhancement, minor

#36 WAC 34 install ckanext googleanalytics
  ckanext/who_afro/templates/package/snippets/resource_item.html
  ckanext/who_afro/templates/snippets/package_item.html
Labels: minor
