Repository fjelltopp/ckanext-who-afro, pull requests merged in 2024-08, with the labels that each got.

#40 feat: add IDSR to programmes
  ckanext/who_afro/presets.json
Labels: minor

#43 feat: add javascript for updating search params when using the new sort options
  ckanext/who_afro/templates/package/search.html
  ckanext/who_afro/templates/snippets/facet_list.html
Labels: enhancement, minor

#47 feat: embed triple billions dashboard
  ckanext/who_afro/assets/css/hero-background.css
  ckanext/who_afro/assets/css/who-afro.css
  ckanext/who_afro/templates/home/snippets/insights.html
  ckanext/who_afro/templates/home/snippets/promoted.html
Labels: minor

#45 fix: update URL for Power BI dashboard on featured insights
  ckanext/who_afro/templates/insights/featured.html
Labels: bug, patch

#41 WAC-121 add really simple data sources pages
  ckanext/who_afro/assets/css/who-afro.css
  ckanext/who_afro/public/images/source-icons/dhis2.png
  ckanext/who_afro/public/images/source-icons/iaho.png
  ckanext/who_afro/public/images/source-icons/website.png
  ckanext/who_afro/public/images/source-icons/who.png
  ckanext/who_afro/templates/countries/index.html
  ckanext/who_afro/templates/sources/index.html
Labels: minor

#42 WAC-116 Indicator datasets
  ckanext/who_afro/assets/css/hero-background.css
  ckanext/who_afro/assets/css/who-afro-dashboard.css
  ckanext/who_afro/assets/css/who-afro.css
  ckanext/who_afro/assets/webassets.yml
  ckanext/who_afro/assets/who-afro-dashboard.js
  ckanext/who_afro/blueprints/__init__.py
  ckanext/who_afro/blueprints/overview.py
  ckanext/who_afro/helpers.py
  ckanext/who_afro/plugin.py
  ckanext/who_afro/public/images/august-14/DH-DataMerge-Graphic.svg
  ckanext/who_afro/templates/countries/index.html
  ckanext/who_afro/templates/insights/featured.html
  ckanext/who_afro/templates/package/base.html
  ckanext/who_afro/templates/package/edit_base.html
  ckanext/who_afro/templates/package/overview.html
  ckanext/who_afro/templates/package/read.html
  ckanext/who_afro/templates/package/read_base.html
  ckanext/who_afro/templates/package/resource_read.html
  ckanext/who_afro/templates/package/snippets/info.html
  ckanext/who_afro/templates/package/snippets/promoted_plus.html
  ckanext/who_afro/templates/page.html
  ckanext/who_afro/templates/scheming/package/read.html
  ckanext/who_afro/templates/scheming/package/resource_read.html
  ckanext/who_afro/templates/scheming/package/snippets/access_use.html
  ckanext/who_afro/templates/scheming/package/snippets/additional_info.html
  ckanext/who_afro/templates/snippets/package_item.html
  ckanext/who_afro/templates/sources/index.html
Labels: major

#50 feat: use latest js for indicator dashboard
  ckanext/who_afro/assets/who-afro-dashboard.js
Labels: bug, patch

#51 fix: use the default header for admin pages
  ckanext/who_afro/templates/admin/base.html
Labels: bug, patch

#52 feat: add climate to list of programmes
  ckanext/who_afro/presets.json
Labels: enhancement, minor

#53 fix: point to malaria dashboard that has a license
  ckanext/who_afro/templates/insights/featured.html
Labels: bug, patch

#56 feat: make the fallback font sans-serif for cleaner loading
  ckanext/who_afro/assets/css/who-afro.css
Labels: minor

#57 feat: make home page photo links work
  ckanext/who_afro/templates/home/snippets/promoted.html
Labels: minor

#59 feat: add more programmes for the GHDH indicators
  ckanext/who_afro/presets.json
  ckanext/who_afro/templates/home/snippets/promoted.html
Labels: minor

#62 feat: add final countries data for country portals
  ckanext/who_afro/assets/css/who-afro.css
  ckanext/who_afro/blueprints/countries.py
  ckanext/who_afro/country_data.csv
  ckanext/who_afro/templates/countries/country.html
Labels: enhancement, minor

#63 fix: make the countries hero container relative positioned so the links are above the background SVG and work
  ckanext/who_afro/assets/css/who-afro.css
Labels: enhancement, minor

#65 feat: add descriptions to data sources
  ckanext/who_afro/assets/css/who-afro.css
  ckanext/who_afro/public/images/source-icons/glass.svg
  ckanext/who_afro/templates/countries/index.html
  ckanext/who_afro/templates/package/read_base.html
  ckanext/who_afro/templates/sources/index.html
Labels: enhancement

#72 feat: make dashboard work with non-facetted indicators
  ckanext/who_afro/helpers.py
  ckanext/who_afro/plugin.py
  ckanext/who_afro/templates/package/overview.html
Labels: enhancement, minor

#73 WAC-136: Small improvements to the UI
  ckanext/who_afro/assets/css/who-afro.css
  ckanext/who_afro/templates/countries/country.html
  ckanext/who_afro/templates/countries/index.html
  ckanext/who_afro/templates/footer.html
  ckanext/who_afro/templates/snippets/facet_list.html
Labels: minor

#74 feat: increase nav bar font size
  ckanext/who_afro/assets/css/who-afro.css
Labels: enhancement, minor

#75 fix: make group search search groups
  ckanext/who_afro/templates/group/read.html
Labels: bug, patch
